---
Metadata:
  conformance: IEEE SA P3109
  version: 3.2.0
  provider: Provider
  contact:
    email: info@implementer.site
    uri: https://implementer.site
  implementation:
    name: release name
    version: 1.0.0
    timestamp: 2026-01-30T20:13Z
  Configurations:
    uri: https://implementer.site/P3109/Implementation/v1.0.0/Configurations.yaml
# reset context
Inference:
  IEEE754: binary32
  Projections:
    Rounding:
      - NearestTiesToEven
      - TowardZero
      - StochasticB:
          - bits: 8
    Saturation:
      - OvfInf
      - SatPropagate
  BlockSizes:
    core: 32
    accelerated: 64
    supported: [32, 64]
  KappaApproximate:
    - SqrtFast
# reset context 
Training:
  IEEE754:
    - binary32
    - binary64
  Projections:
    Rounding:
      - NearestTiesToEven
      - TowardNegative
      - TowardPositive
      - StochasticB:
          - bits: (' Minimum(PrecisionOf(fx), 16) ')
          - notes:
              - description: xoroshiro128++ using top 16 bits.
              - reference:
                  uri: >
                    https://implementer.site/P3109/Implementation/v1.0.0/
                    Stochastic/Xoshiro128plusplus.c
    Saturation:
      - OvfInf
      - SatFinite
  BlockSizes:
    core: [16, 32]
    accelerated: 64
    supported: (' "2^$(i)" for i in 4:24 ')
  KappaApproximate:
    - SqrtFast
    - ExpFast:
        - ExpFast.1
        - ExpFast.2