---
Metadata:
  conformance: "IEEE SA P3109"
  version: "3.2.0"
  provider: "Provider"
  contact:
    email: info@implementer.site
    uri: https://implementer.site
  implementation:
    name: "release name"
    version: "1.0.0"
    timestamp: 2026-01-24T19:30Z
    uri: https://implementer.site/P3109/Implementation/v1.0.0/Profiles.yaml

Core32:
  formats:
    - Binary8p3se
    - Binary8p4se

Core64:
  formats:
    - ( 'Binary4p$(i)sf' for i in 1:3 )
    - ( 'Binary8p$(i)se' for i in [3,4] )
